---
title: "scrapping"
author: "Jesús Yancy"
date: "2025-08-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Set working directory
username <- Sys.getenv("USER")

if (username == "jesusyancy"){
  path <- "/Users/jesusyancy/Documents/MECA/BDML/TALLERES/TALLER 1"
} else if(username == ''){
  path <- ""
}
setwd(path)
```

```{r}
library(pacman)
```

```{r}
# Instalar paquetes
p_load(rio, # import/export data
       tidyverse, # tidy-data
       skimr, # summary data
       visdat, # visualizing missing data
       corrplot, # Correlation Plots 
       stargazer) # tables/output to TEX.
```

```{r}
df <- import("https://raw.githubusercontent.com/jrconstain/PS1_Group4/refs/heads/main/data/data.csv?token=GHSAT0AAAAAADJKTLBWWIRCU3OS4ZXHVJHS2FU5VTA")
```

```{r}
# Filtrar las observaciones: Ocupados/empleados y mayores o iguales a 18 años
df_18 <- df %>%
  filter(ocu == 1 & dsi == 0 & age >= 18)
```

```{r}
# Crear un df que contiene solo las variables que usaríamos en los modelos.
df_modelos <- df_18 %>%
  mutate(age2 = age^2) %>%
  select(directorio, secuencia_p, orden, clase, dominio,
         y_total_m_ha, y_salary_m_hu, y_ingLab_m_ha,
         y_total_m, y_salary_m, y_ingLab_m, y_salarySec_m,
         ingtot, ingtotob, age, age2, maxEducLevel, college, p6210, p6210s1,
         p6426, oficio, p6240, sizeFirm, relab, formal, cuentaPropia,
         microEmpresa, sex, hoursWorkUsual, totalHoursWorked, ocu, dsi)

```

```{r}



```



Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
