name: LaTeX Build

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: document/Document.tex   # ← ajusta si tu .tex tiene otro nombre
          work_in_root_file_dir: true        # compila desde la carpeta del .tex
          extra_system_packages: "ghostscript" # útil para algunas inclusiones de figuras

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: document/Document.pdf        # el PDF queda junto al .tex

