name: Build LaTeX document

on:
  push:
    branches: [ main ]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Compile LaTeX
      uses: xu-cheng/latex-action@v2
      with:
        root_file: Document.tex   # o Exam.tex según el caso

    - name: Upload PDF as artifact
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: Document.pdf
