name: Build & Publish LaTeX PDF

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'document/Document.pdf'   # evita loop cuando sólo cambia el PDF

permissions:
  contents: write   # necesario para poder commitear al repo

jobs:
  build_publish_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          root_file: document/Document.tex   # ajusta si tu archivo tiene otro nombre
          work_in_root_file_dir: true
          extra_system_packages: "ghostscript"

      # Commitea el PDF generado si hubo cambios
      - name: Commit PDF back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-build Document.pdf [skip ci]'
          file_pattern: 'document/Document.pdf'
          branch: main
